export const GET_SERVER_CONSTANTS_REQUEST = "GET_SERVER_CONSTANTS_REQUEST";
export const GET_SERVER_CONSTANTS_PASS = "GET_SERVER_CONSTANTS_PASS";
export const GET_SERVER_CONSTANTS_FAIL = "GET_SERVER_CONSTANTS_FAIL";