export const MESSAGE_TYPE_SUCCESS = "MESSAGE_TYPE_SUCCESS";
export const MESSAGE_TYPE_DANGER = "MESSAGE_TYPE_DANGER";
export const MESSAGE_TYPE_WARNING = "MESSAGE_TYPE_WARNING";
export const MESSAGE_TYPE_INFO = "MESSAGE_TYPE_INFO";